services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresql-server
    ports:
      - "5432:5432"
    volumes:
      - /mnt/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: password
      POSTGRES_DB: otusdb
    networks:
      - postgre
networks:
  postgre:
    name: postgre
    driver: bridge