# postgres_backup_playbook.yml
---
- name: Deploy PostgreSQL Backup Script and Service
  hosts: cloudru
  become: yes
  tasks:
    - name: Ensure backup directory exists
      file:
        path: /mnt/backups
        state: directory
        owner: postgres
        group: postgres
        mode: "0744"

    - name: Copy backup script
      copy:
        src: backup/fullbackup.sh
        dest: /usr/local/bin/fullbackup.sh
        owner: postgres
        group: postgres
        mode: "0755"

    - name: Create systemd service for PostgreSQL backup
      copy:
        src: backup/postgres-backup.service
        dest: /etc/systemd/system/postgres-backup.service
        owner: root
        group: root
        mode: "0644"

    - name: Create systemd timer for PostgreSQL backup
      copy:
        src: backup/postgres-backup.timer
        dest: /etc/systemd/system/postgres-backup.timer
        owner: root
        group: root
        mode: "0644"

    - name: Enable and start the backup timer
      systemd:
        name: postgres-backup.timer
        enabled: yes
        state: started
